### PR TITLE
[finishes #160128788] Adding index.html and style.css in my project

### PR DESCRIPTION
**Pull request by joelethan**
Initial changes made to my Project..

### CODE REVIEW

**Comment by kyakusahmed** [comment]
good staff joel

**Comment by Luleherll** [comment]
Add a brief description.

**Comment by Luleherll** [comment]
add a brief description.

**Comment by walimike** [comment]
This is dop, however, use present tense in your commits

**Comment by mariamiah** [comment]
good work

**Comment by mulondo** [comment]
its fine

**Pull request merged**
